### ISSUE TITLE
[Bug]: Does not handle more than 1 exclusions

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/r-spellcheck-action#9]
### What happened?

Action fails when `exclude = <exclusions>` has more than 1 item.

Recent CI failure: https://github.com/atorus-research/xportr/actions/runs/7742655713/job/21112263390

``` r
exclusions <- c("ads", "asd")
if (!is.na(exclusions)) 1
#> Error in if (!is.na(exclusions)) 1: the condition has length > 1
```

<sup>Created on 2024-02-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This should resolve the problem:

```diff
diff --git a/spellcheck.R b/spellcheck.R
index 9d33283..40c8d5c 100755
--- a/spellcheck.R
+++ b/spellcheck.R
@@ -5,7 +5,7 @@ exclusions <- strsplit(args[1], ",")[[1]]
 
 # Temporarily delete excluded files
 removed <- FALSE
-if (! is.na(exclusions)) removed <- lapply(Sys.glob(exclusions), file.remove)
+if (any(!is.na(exclusions))) removed <- lapply(Sys.glob(exclusions), file.remove)
 
 spell_check_result <- spelling::spell_check_package(
     vignettes = TRUE,
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by cicdguy** [comment]
Thanks for the report, @averissimo! We'll push out a fix ASAP.
